### ISSUE TITLE
Secure dashboard and api with basic auth

### ISSUE THREAD

**Issue by platomaniac** [BashfulBandit/docker-traefik#2]
I tried to add the basic auth to your setup but did not work right away.

We should add basic authentication and a rate limit via traefik on the authentication endpoint.

Two examples here which I found useful in my previous setup are here:

- https://blog.birkhoff.me/serve-traefiks-internal-dashboard-behind-traefik/
- https://medium.com/@xavier.priour/secure-traefik-dashboard-with-https-and-password-in-docker-5b657e2aa15f

Rate limiting:
https://github.com/containous/traefik/issues/4576

Cheers :)

**Comment by jdtempleton** [comment]
Hey @platomaniac 

I haven't made Basic Auth a part of the initial set up of the environment, but there is an example in both `docker-compose.container.yml` and `docker-compose.swarm.yml`. 

```yml
- traefik.frontend.auth.basic.users=${USERNAME}:${HASHED_PASSWORD}
```

The only thing you would need to do is add and define the `USERNAME` and `HASHED_PASSWORD` variables in your `.env` file. The [Traefik Docs](https://docs.traefik.io/configuration/entrypoints/#basic-authentication) define what valid hashes they support and recommendations on how to generate the `HASHED_PASSWORD`.

**Comment by jdtempleton** [comment]
I didn't mean to close the issue.

**Comment by platomaniac** [comment]
My bad it has indeed been solved. I was having some typo.

**Comment by jdtempleton** [comment]
Hey @platomaniac 

Glad to hear you figured it out. I will also look into possibly adding the rate limiting feature. I honestly don't think it falls into the scope of what this repository is for though. I initially set up the repository to make an easy way for someone to setup their basic Traefik with Let's Encrypt in either a basic Docker Container set up or in a Docker Swarm since I have seen and heard a lot of people having trouble setting this up. I do mention in the repositories README.md there are many other configurations to add to this, like Basic Auth, and those can be easily added after taking a look at the Traefik Documentation. 

Thanks!

**Comment by platomaniac** [comment]
@BashfulBandit I also think this repo should be sleek and easy and the rate limiting stuff is very specific. You are right that we better keep it without such specific things. One though came to my mind though, will the current setup work in a Swarm that has multiple manager nodes? How the acme certificate will be saved in that case. A simple way without consul and stuff will be nice.

**Comment by jdtempleton** [comment]
@platomaniac Since the `acme.json` is a part of a bind mount to a local directory in the repository as `- ./traefik:/etc/traefik`, the way I set up multiple nodes in a Docker Swarm is by using NFS mounts. For example, I have a single directory I NFS mount across all of my Docker Nodes. I then run all of my Docker environments from within the NFS directory. This way they share the same directories and files across all of the Swarm Nodes. 

So to answer your question, yes this setup will work with multiple manager nodes within a Docker Swarm. You just have to configure your system to share files and directories across those nodes.

**Comment by platomaniac** [comment]
@BashfulBandit thanks for the info I also got NFS setup working. However in my case I host the NFS on one of my swarm nodes at the moment. Thus I actually do not achieve the HA as in case this NFS server node goes down all other Traefik manager nodes that mounted the share will suffer.

Have you ever tried Consul KV store with Traefik. Unfortunately I could not get this to work after several attempts. So for now staying with NFS. But a HA consul with replica will be nice. Here is a stack I tried with Consul in case you want to give it a try.

## My Consul try
I consistently see that the consul replicas can not connect to the consul leader.
What did I do wrong here? Is it because of the UFW firewall but I really doubt that, as docker swarm should take over the routing. Any ideas will be really appreciated.

## Traefik error
Traefik service gives this error:

```shell
level=error msg="Load config error: Get http://consul-leader:8500/v1/kv/traefik?consistent=&recurse=&wait=30000ms: dial tcp 10.0.2.12:8500: i/o timeout, retrying in 727.936874ms"
```

## My stack file (adapted from this repo)

```yml
# Define which version of docker-compose file you are using.
version: '3.7'

# Traefik Docker Stack for Docker Swarm with Consul
services:
  consul-leader:
    image: consul:1.5
    command: agent -server -client=0.0.0.0 -bootstrap -ui
    volumes:
      - consul-data-leader:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth1
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - traefik-consul
    deploy:
      labels:
        - traefik.frontend.rule=Host:consul.${DOMAIN}
        - traefik.backend=consul-leader
        - traefik.enable=true
        - traefik.port=8500
        - traefik.docker.network=proxy-net
        - traefik.frontend.auth.basic.users=${USERNAME}:${HASHED_PASSWORD}

  consul-replica:
    image: consul:1.5
    command: agent -server -client=0.0.0.0 -retry-join="consul-leader"
    volumes:
      - consul-data-replica:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth1
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - traefik-consul
    deploy:
      replicas: ${CONSUL_REPLICAS:-2}
      placement:
        constraints:
          - node.role == manager # Data ceneter, 'spread=node.labels.datacenter, datacenter=us-west,
  # Traefik Reverse-Proxy Service
  traefik:
    image: traefik:v1.7
    networks:
      - traefik-consul
      - traefik-proxy-network
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    # These options are only used in Docker Swarm via docker stack deploy.
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.frontend.rule=Host:monitor.${DOMAIN}
        - traefik.enable=true
        - traefik.port=8080
        - traefik.docker.network=proxy-net
        - traefik.frontend.auth.basic.users=${USERNAME}:${HASHED_PASSWORD}
        - traefik.frontend.headers.forceSTSHeader=true
        - traefik.frontend.headers.STSSeconds=315360000
        - traefik.frontend.headers.STSIncludeSubdomains=true
        - traefik.frontend.headers.STSPreload=true
        - traefik.backend.loadbalancer.swarm=true
        - traefik.backend.loadbalancer.method=drr

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    command: >
      --docker
      --docker.swarmmode
      --docker.watch
      --docker.exposedbydefault=false
      --api
      --consul
      --consul.endpoint=consul-leader:8500
      --logLevel=INFO
      --accessLog
      --docker.swarmModeRefreshSeconds=5
      --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
      --entrypoints=Name:https Address::443 TLS
      --acme
      --acme.email=${EMAIL}
      --acme.storage=traefik/acme/account
      --acme.entrypoint=https
      --acme.tlsChallenge=true
      --acme.onhostrule=true
      --acme.acmelogging=true

# Traefik Docker Networks for Docker Swarm
networks:
  traefik-proxy-network:
    name: proxy-net
    attachable: true
  traefik-consul:
    driver: overlay
    attachable: true
    name: traefik-consul
    driver_opts:
      encrypted: "true"

volumes:
  consul-data-leader:
  consul-data-replica:
```
## Consul log (Leader)
Here is consul log:

```shell
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    | ==> Found address '172.18.0.3' for interface 'eth1', setting bind option...
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    | bootstrap = true: do not enable unless necessary
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    | ==> Starting Consul agent...
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |            Version: 'v1.5.3'
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |            Node ID: 'd59afb82-d9af-425f-9380-cac26e5dac09'
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |          Node name: '8c1a5cc7ed3e'
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |         Datacenter: 'dc1' (Segment: '<all>')
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |             Server: true (Bootstrap: true)
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |        Client Addr: [0.0.0.0] (HTTP: 8500, HTTPS: -1, gRPC: -1, DNS: 8600)
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |       Cluster Addr: 172.18.0.3 (LAN: 8301, WAN: 8302)
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |            Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false, Auto-Encrypt-TLS: false
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    | 
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    | ==> Log data will now stream in as it occurs:
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    | 
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |     2019/07/27 18:24:21 [INFO]  raft: Initial configuration (index=1): [{Suffrage:Voter ID:d59afb82-d9af-425f-9380-cac26e5dac09 Address:172.18.0.3:8300}]
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |     2019/07/27 18:24:21 [INFO] serf: EventMemberJoin: 8c1a5cc7ed3e.dc1 172.18.0.3
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |     2019/07/27 18:24:21 [INFO] serf: EventMemberJoin: 8c1a5cc7ed3e 172.18.0.3
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |     2019/07/27 18:24:21 [INFO] agent: Started DNS server 0.0.0.0:8600 (udp)
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |     2019/07/27 18:24:21 [INFO]  raft: Node at 172.18.0.3:8300 [Follower] entering Follower state (Leader: "")
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |     2019/07/27 18:24:21 [INFO] consul: Handled member-join event for server "8c1a5cc7ed3e.dc1" in area "wan"
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |     2019/07/27 18:24:21 [INFO] consul: Adding LAN server 8c1a5cc7ed3e (Addr: tcp/172.18.0.3:8300) (DC: dc1)
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |     2019/07/27 18:24:21 [INFO] agent: Started DNS server 0.0.0.0:8600 (tcp)
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |     2019/07/27 18:24:21 [INFO] agent: Started HTTP server on [::]:8500 (tcp)
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |     2019/07/27 18:24:21 [INFO] agent: started state syncer
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    | ==> Consul agent running!
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |     2019/07/27 18:24:28 [ERR] agent: failed to sync remote state: No cluster leader
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |     2019/07/27 18:24:28 [WARN]  raft: Heartbeat timeout from "" reached, starting election
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |     2019/07/27 18:24:28 [INFO]  raft: Node at 172.18.0.3:8300 [Candidate] entering Candidate state in term 2
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |     2019/07/27 18:24:28 [INFO]  raft: Election won. Tally: 1
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |     2019/07/27 18:24:28 [INFO]  raft: Node at 172.18.0.3:8300 [Leader] entering Leader state
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |     2019/07/27 18:24:28 [INFO] consul: cluster leadership acquired
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |     2019/07/27 18:24:28 [INFO] consul: New leader elected: 8c1a5cc7ed3e
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |     2019/07/27 18:24:28 [INFO] consul: member '8c1a5cc7ed3e' joined, marking health alive
traefik_consul-leader.1.8g0muy3wmzm8@zabo-dev-worker-02    |     2019/07/27 18:24:30 [INFO] agent: Synced node info
```
## Consul Replica log

```shell
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    | ==> Found address '172.18.0.4' for interface 'eth1', setting bind option...
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    | ==> Starting Consul agent...
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |            Version: 'v1.5.3'
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |            Node ID: '92fd8f94-853c-b916-69a9-ccefb76128c3'
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |          Node name: '7476db8ebed0'
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |         Datacenter: 'dc1' (Segment: '<all>')
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |             Server: true (Bootstrap: false)
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |        Client Addr: [0.0.0.0] (HTTP: 8500, HTTPS: -1, gRPC: -1, DNS: 8600)
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |       Cluster Addr: 172.18.0.4 (LAN: 8301, WAN: 8302)
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |            Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false, Auto-Encrypt-TLS: false
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    | 
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    | ==> Log data will now stream in as it occurs:
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    | 
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:18 [INFO]  raft: Initial configuration (index=0): []
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:18 [INFO] serf: EventMemberJoin: 7476db8ebed0.dc1 172.18.0.4
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:18 [INFO] serf: EventMemberJoin: 7476db8ebed0 172.18.0.4
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:18 [INFO] agent: Started DNS server 0.0.0.0:8600 (udp)
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:18 [INFO]  raft: Node at 172.18.0.4:8300 [Follower] entering Follower state (Leader: "")
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:18 [INFO] consul: Adding LAN server 7476db8ebed0 (Addr: tcp/172.18.0.4:8300) (DC: dc1)
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:18 [INFO] consul: Handled member-join event for server "7476db8ebed0.dc1" in area "wan"
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:18 [INFO] agent: Started DNS server 0.0.0.0:8600 (tcp)
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:18 [INFO] agent: Started HTTP server on [::]:8500 (tcp)
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:18 [INFO] agent: started state syncer
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    | ==> Consul agent running!
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:18 [INFO] agent: Retry join LAN is supported for: aliyun aws azure digitalocean gce k8s mdns os packet scaleway softlayer triton vsphere
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:18 [INFO] agent: Joining LAN cluster...
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:18 [INFO] agent: (LAN) joining: [consul-leader]
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:18 [WARN] memberlist: Failed to resolve consul-leader: lookup consul-leader on 127.0.0.11:53: no such host
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:18 [WARN] agent: (LAN) couldn't join: 0 Err: 1 error occurred:
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |  * Failed to resolve consul-leader: lookup consul-leader on 127.0.0.11:53: no such host
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    | 
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:18 [WARN] agent: Join LAN failed: <nil>, retrying in 30s
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:25 [ERR] agent: failed to sync remote state: No cluster leader
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:26 [WARN]  raft: no known peers, aborting election
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:48 [INFO] agent: (LAN) joining: [consul-leader]
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:48 [ERR] agent: Coordinate update error: No cluster leader
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:49 [ERR] agent: failed to sync remote state: No cluster leader
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |     2019/07/27 18:24:58 [WARN] agent: (LAN) couldn't join: 0 Err: 1 error occurred:
traefik_consul-replica.1.l7u4f5fn03hu@zabo-dev-03    |  * Failed to join 10.0.2.12: dial tcp 10.0.2.12:8301: i/o timeout
```
